### ISSUE TITLE
Regarding your question on a humulus annotation

### ISSUE THREAD

**Issue by shrhops** [amizeranschi/datasciencecoursera#1]
Hello! 
I'm working on a de novo assembly of Hops, and I've come across the same issue as you (no GTF/GFF3 file available online). I saw that another commenter recommended using the available resources on HopBase, but I cannot find a GFF3 file like they said, under the CascadeHaplotigs section. Were you able to do it through that channel? Alternately, do you have a publicly avaialable annotation file Hops? 

thanks,
Shraddha

**Comment by amizeranschi** [comment]
Hi!

I gave up on that idea before even starting it, so I've never actually got to work with Hops. I couldn't find an annotation file after a quick Google search now, so you might want to consider creating one yourself, if you have the time and resources (you would need RNA-seq data for this).

Have a look at functional genome annotation / transcriptome assembly: https://en.wikipedia.org/wiki/DNA_annotation

AUGUSTUS is one of the more popular tools, but I think it can be a little difficult to set up and use: https://pubmed.ncbi.nlm.nih.gov/31020558/

However, it sometimes comes integrated into more automated pipelines, for example: 
https://github.com/Gaius-Augustus/BRAKER
https://link.springer.com/protocol/10.1007/978-1-4939-9173-0_3

Good luck!
